### ISSUE TITLE
Don’t include commented out items in the outline

### ISSUE THREAD

**Issue by DmitrySharabin** [h-tex/eleventy-plugin-outline#2]
For example, this figure will be picked up even though it shouldn't:

```html
<!-- <figure>

![](figures/reviews.png)

<figcaption>

</figcaption>

</figure> -->
```

**Comment by LeaVerou** [comment]
This should be an easy fix

**Comment by LeaVerou** [comment]
Actually it may be a little trickier: the easy way would be to strip comments, but we want to preserve them because other plugins process them (e.g. todos). So I guess we need to check, for each match, whether it’s within a comment. 

One easy way I can think of to do this would be to tweak the regex that matches the headings/figures to *also* match `<!--` and `-->`. Then we set flags accordingly so that we know that we’re inside a comment.
